# Generated by Django 4.0.1 on 2022-01-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='api_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='api_id',
            field=models.CharField(max_length=255),
        ),
    ]
