# Generated by Django 4.0.4 on 2022-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_details_api_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
