# Generated by Django 4.0.4 on 2022-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='emulator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
