# Generated by Django 4.0.4 on 2022-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inactive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='comment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
