# Generated by Django 4.0.4 on 2022-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_user_details_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='comment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
