# Generated by Django 4.0.4 on 2022-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_inactive_user_created_at_inactive_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='banned',
            field=models.CharField(default='NOT BANNED', max_length=255),
            preserve_default=False,
        ),
    ]
