# Generated by Django 4.0.4 on 2022-06-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_details_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='banned',
        ),
    ]
