# Generated by Django 4.0.4 on 2022-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_user_details_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='banned',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('FLOOD WAIT', 'FLOOD WAIT'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=255),
        ),
    ]
