# Generated by Django 4.0.4 on 2022-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_details_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='comment',
            field=models.IntegerField(default='ACTIVE'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='views',
            field=models.IntegerField(default='ACTIVE'),
        ),
    ]
