# Generated by Django 4.0.4 on 2022-06-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_user_details_comment_alter_user_details_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
