# Generated by Django 3.2.3 on 2022-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220609_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_view',
            name='comment_on',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
