# Generated by Django 3.2.3 on 2022-06-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_comment_view_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_view',
            name='view_on',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
