# Generated by Django 4.0.4 on 2022-06-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_engagement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='engagement',
            new_name='Engagements',
        ),
    ]
