# Generated by Django 4.0.4 on 2022-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_engagement_engagements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='reaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='banned',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('FLOOD WAIT', 'FLOOD WAIT'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED'), ('NEED PASSWORD', 'NEED PASSWORD')], default='ACTIVE', max_length=255),
        ),
    ]
