# Generated by Django 4.0.4 on 2022-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_user_details_reaction_alter_user_details_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inactive_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='comment_view',
        ),
        migrations.DeleteModel(
            name='Engagements',
        ),
        migrations.DeleteModel(
            name='inactive_user',
        ),
    ]
