# Generated by Django 4.0.4 on 2022-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_user_details_reaction_inactive_user_engagements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagements',
            name='message_on',
            field=models.IntegerField(default=0),
        ),
    ]
