# Generated by Django 4.0.4 on 2022-06-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_view_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='views_on',
            field=models.IntegerField(default=0),
        ),
    ]
