# Generated by Django 4.0.4 on 2022-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_view_views_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='message_on',
        ),
        migrations.AlterField(
            model_name='view',
            name='views_on',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
