# Generated by Django 4.0.4 on 2022-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_view_message_on_alter_view_views_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_view',
            name='comment',
            field=models.TextField(default='-'),
        ),
    ]
