# Generated by Django 4.0.4 on 2022-06-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_comment_view_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='banned',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('NOT AUTHORIZED', 'NOT AUTHORIZED'), ('FLOOD WAIT', 'FLOOD WAIT'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED'), ('NEED PASSWORD', 'NEED PASSWORD')], default='ACTIVE', max_length=255),
        ),
    ]
