# Generated by Django 4.0.4 on 2022-06-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_user_details_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='banned',
            new_name='status',
        ),
    ]
