# Generated by Django 4.0.4 on 2022-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_banned_user_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactive_user',
            name='status',
            field=models.CharField(choices=[('NOT AUTHORIZED', 'NOT AUTHORIZED'), ('FLOOD WAIT', 'FLOOD WAIT'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED'), ('NEED PASSWORD', 'NEED PASSWORD')], default='ACTIVE', max_length=255),
        ),
    ]
