# Generated by Django 4.0.4 on 2022-06-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_inactive_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inactive_user',
        ),
    ]
