# Generated by Django 4.0.4 on 2022-06-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_delete_inactive_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='inactive_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT AUTHORIZED', 'NOT AUTHORIZED'), ('FLOOD WAIT', 'FLOOD WAIT'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED'), ('NEED PASSWORD', 'NEED PASSWORD')], default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_details')),
            ],
        ),
    ]
