# Generated by Django 4.0.4 on 2022-06-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_inactive_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engagements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.DeleteModel(
            name='comment_view',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='Engagements',
        ),
        migrations.DeleteModel(
            name='view',
        ),
    ]
