# Generated by Django 4.0.4 on 2022-06-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_view_engagements_comments_comment_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='views',
        ),
    ]
