# Generated by Django 4.0.4 on 2022-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_user_details_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='reaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
