# Generated by Django 4.1 on 2022-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_user_details_comment_user_details_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='message_on',
            field=models.IntegerField(default=0),
        ),
    ]
